Console.WriteLine("number1= ");
int a = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("number2= ");
int b = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("number3= ");
int c = Convert.ToInt32(Console.ReadLine());
int max = a;
if (max < b) max = b; 
if (max < c) max = c; 
System.Console.WriteLine(max);